apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  creationTimestamp: null
  labels:
    build: mlbparks-pipeline
  name: mlbparks-pipeline
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: mlbparks:latest
  postCommit: {}
  resources: {}
  source:
    git:
      uri: https://github.com/tjachja/advdev_homework.git
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: MLBParks/Jenkinsfile
  triggers:  
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0