apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  creationTimestamp: null
  labels:
    build: nationalparks-pipeline
  name: nationalparks-pipeline
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: nationalparks:latest
  postCommit: {}
  resources: {}
  source:
    git:
      uri: https://github.com/tjachja/advdev_homework.git
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Nationalparks/Jenkinsfile
  triggers:
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0